//
// NamedPipeStream.cpp
//
// $Id: //poco/1.4/Foundation/src/NamedPipeStream.cpp#2 $
//
// Library: Foundation
// Package: Processes
// Module:  NamedPipeStream
//
// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include "Poco/NamedPipeStream.h"


namespace Poco {


//
// NamedPipeStreamBuf
//


NamedPipeStreamBuf::NamedPipeStreamBuf(const NamedPipe& pipe, openmode mode): 
	BufferedStreamBuf(STREAM_BUFFER_SIZE, mode),
	_pipe(pipe)
{
}


NamedPipeStreamBuf::~NamedPipeStreamBuf()
{
}


int NamedPipeStreamBuf::readFromDevice(char* buffer, std::streamsize length)
{
	return _pipe.readBytes(buffer, (int) length);
}


int NamedPipeStreamBuf::writeToDevice(const char* buffer, std::streamsize length)
{
	return _pipe.writeBytes(buffer, (int) length);
}


void NamedPipeStreamBuf::close()
{
	_pipe.close(NamedPipe::CLOSE_BOTH);
}


//
// NamedPipeIOS
//


NamedPipeIOS::NamedPipeIOS(const NamedPipe& pipe, openmode mode):
	_buf(pipe, mode)
{
	poco_ios_init(&_buf);
}


NamedPipeIOS::~NamedPipeIOS()
{
	try
	{
		_buf.sync();
	}
	catch (...)
	{
	}
}


NamedPipeStreamBuf* NamedPipeIOS::rdbuf()
{
	return &_buf;
}


void NamedPipeIOS::close()
{
	_buf.sync();
	_buf.close();
}


//
// NamedPipeOutputStream
//


NamedPipeOutputStream::NamedPipeOutputStream(const NamedPipe& pipe):
	NamedPipeIOS(pipe, std::ios::out),
	std::ostream(&_buf)
{
}


NamedPipeOutputStream::~NamedPipeOutputStream()
{
}


//
// NamedPipeInputStream
//


NamedPipeInputStream::NamedPipeInputStream(const NamedPipe& pipe):
	NamedPipeIOS(pipe, std::ios::in),
	std::istream(&_buf)
{
}


NamedPipeInputStream::~NamedPipeInputStream()
{
}


} // namespace Poco
